title: Rodrigo P.  # You can add your name here

logo: foto-perfil.jpeg # Use a relative path to logo image 

description: Fullstack Developer - eager to learn, collaborate, and share insights with fellow professionals.

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: rodrigoportugaldutra@gmail.com # Allow visitors to contact you
